### PR TITLE
Added stlconductor module

### PR DESCRIPTION
**Pull request by yhu-radiasoft**

### CODE REVIEW

**Comment by ncook882** [comment]
Thanks for the pull request, @yhu-radiasoft. I was able to run all example files and use the STLconductor API. The main comments that I have are on the documentation of code and example notebooks. This comment addresses the code  documentation. In a follow up comment I'll give some recommendations for the example notebook documentation and push a revised example.

For the STLconductor class, you should make the docstrings [PEP-257](https://www.python.org/dev/peps/pep-0257/) compliant. In particular multi-line docstrings should follow this advice:

> Multi-line docstrings consist of a summary line just like a one-line docstring, followed by a blank line, followed by a more elaborate description. The summary line may be used by automatic indexing tools; it is important that it fits on one line and is separated from the rest of the docstring by a blank line

Many of the member functions in the STLconductor class have a one-line summary comment followed by multiple lines of single line # comments. These should be incorporated into the headline comment.

Next, I’d recommend following the [Google Style Guide](http://google.github.io/styleguide/pyguide.html) for documenting arguments:

> Args:
> 
> List each parameter by name. A description should follow the name, and be separated by a colon and a space. If the description is too long to fit on a single 80-character line, use a hanging indent of 2 or 4 spaces (be consistent with the rest of the file).
> The description should include required type(s) if the code does not contain a corresponding type annotation.
> If a function accepts *foo (variable length argument lists) and/or **bar (arbitrary keyword arguments), they should be listed as *foo and **bar.
> 
> Returns: (or Yields: for generators)
> Describe the type and semantics of the return value. If the function only returns None, this section is not required. It may also be omitted if the docstring starts with Returns or Yields (e.g. """Returns row from Bigtable as a tuple of strings.""") and the opening sentence is sufficient to describe return value.
> 
> Raises:
> List all exceptions that are relevant to the interface.

**Comment by ncook882** [comment]
In ced9b94 I've revised the simple STL grid example notebook with the following changes:

- Added Introductory comments
- Added a switch for using both ray-triangle intersection schemes
- Adjusted the z-y phi plot to determine the aspect ratio automatically

Similar changes should probably be made to the other example notebooks, although you may keep the ray-triangle scheme fixed as `watertight` for the more advanced geometries.

**Comment by yhu-radiasoft** [comment]
@ncook882 I have just pushed a commit, which has revised the docstrings and some comments. Please have a look.

**Comment by ncook882** [comment]
Thanks @yhu-radiasoft for the helpful changes. At this point, I'm done with my review, so I'll go ahead and approve the pull request.

**Comment by yhu-radiasoft** [comment]
Thank you @ncook882

**Pull request merged**
